backend = "glx";
vsync = true;
use-damage = false;

blur:
{
  method = "gaussian";
  size = 20;
  deviation = 15.0;
};

opacity-rule = [
  "15:class_g = 'i3lock'"
];

blur-background-exclude = [
  "class_g = 'i3lock'",
];
