[font]
size = 11.0

[font.bold]
family = "Madimi One"
style = "Bold"

[font.bold_italic]
family = "Madimi One"
style = "Bold Italic"

[font.italic]
family = "Madimi One"
style = "Italic"

[font.normal]
family = "Madimi One"
style = "Regular"

[cursor.style]
shape = "Underline"
blinking = "On"

[colors.primary]
background = "#130909"

[shell]
program = "/bin/bash"
args  = ["-c", "/bin/neofetch && exec bash"]
