[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
opacity= 0.95

[cursor]
style = { shape = "Underline", blinking = "Off" }

[font]
size = 11.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]
