vim.g.startup_start = vim.uv.hrtime()

require("options")
require("keymaps")
require("plugins")
require("lsp")
require("autocmds")
require("blink")
require("treesitter")
require("fzf")
require("autopairs")
require("startup")
