# i3bar configuration

bar {
   position bottom
   status_command i3status-rs ~/.config/i3/i3status.toml
   font pango:Iosevka Nerd Font 10
   mode hide
   colors {
          background $base
          statusline $text
          separator $overlay0
          #                 border  bground  text
          focused_workspace  $mauve  $mauve  $base
          active_workspace   $surface1 $surface1 $text
          inactive_workspace $base  $base  $overlay1
          urgent_workspace   $red   $red   $base
   }
  
}

bindsym $mod+i bar mode toggle
