# Resize mode
# I don't like resize mode so I have these keybinds instead

bindsym $mod+Left resize shrink width 10 px
bindsym $mod+Down resize grow height 10 px
bindsym $mod+Up resize shrink height 10 px
bindsym $mod+Right resize grow width 10 px
bindsym $mod+Shift+Left resize shrink width 50 px
bindsym $mod+Shift+Down resize grow height 50 px
bindsym $mod+Shift+Up resize shrink height 50 px
bindsym $mod+Shift+Right resize grow width 50 px


