# Variables and input configuration

# Logo key. Use Mod1 for Alt.
set $mod Mod4
# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l
# Your preferred terminal emulator
set $term alacritty
# Your preferred application launcher
set $menu ~/.config/rofi/menus-launcher

# Wallpaper
exec_always --no-startup-id feh --bg-scale ~/.config/wallpaper.jpg

# Input configuration
exec_always --no-startup-id setxkbmap -layout us -variant altgr-intl

# Pointer acceleration
exec_always --no-startup-id xinput set-prop "libinput Accel Speed" --float 1.0

# Display resolution
exec_always --no-startup-id autorandr -l default

#Picom 
exec_always --no-startup-id picom

# Auto-start apps
exec --no-startup-id nm-applet
exec --no-startup-id librewolf
exec --no-startup-id discord
exec --no-startup-id spotify-launcher
exec --no-startup-id steam -silent
exec --no-startup-id whatsapp
exec --no-startup-id ~/.config/i3/spotify_stat

# Move apps to workspace 10
assign [class="discord"] 10
assign [class="Spotify"] 10
assign [class="Chromium" title="WhatsApp Web"] 10
