#!/bin/bash

eval $(xdotool getwindowfocus getwindowgeometry --shell 2>/dev/null)

if [ "$X" != "-1" ] && [ ! -z "$WIDTH" ]; then
    xdotool mousemove --window $(xdotool getwindowfocus) $((WIDTH/2)) $((HEIGHT/2))
fi
